### ISSUE TITLE
Integrate Jaeger

### ISSUE THREAD

**Issue by icebergdelphi** [VeritasSoftware/AspNetCore.ApiGateway#1]
Hi  I have a doubt , I wonder myself if is possible integrate OpenTracing (Jaeger) due I need to Monitoring The request From APIGateway to Final API? Thank you.

**Comment by VeritasSoftware** [comment]
Hi,

You should be able to add Jaeger tracing in your gateway api project and your final api.

This article, explains more.
[Jaeger](https://www.c-sharpcorner.com/article/exploring-distributed-tracing-using-asp-net-core-and-jaeger/)

**Comment by VeritasSoftware** [comment]
Closing issue.
