### ISSUE TITLE
Unable to get data using WeatherService

### ISSUE THREAD

**Issue by divyeshdesanisos** [VeritasSoftware/AspNetCore.ApiGateway#3]
Hi @VeritasSoftware,

I have cloned the repository and trying to debug the whole process.

I have few questions:
1. Do I need to keep all projects running? For now I kept all projects running.
 - There was one error regarding SignalR - so I modified AspNetCore.ApiGateway -> Startup.cs -> ConfigureService part.
2. Which project needs to keep as startup project?
3. When trying to execute the weather service getting error. Refer screenshot for more details.
![image](https://user-images.githubusercontent.com/96718718/147667963-419f2691-7673-421e-9ab2-bda9228a9e1a.png)

Let me know if you need more details.

Thanks in advance.

**Comment by VeritasSoftware** [comment]
Hi, 

Keep the below projects (multiple) running on start up.

![image](https://user-images.githubusercontent.com/2626687/147693229-0cdfe4c3-86bc-4b75-8c30-83b1fce9ea91.png)
 
Also, make sure, the backend weather service & stock service urls are properly specified in Api Orchestrator.

**Comment by divyeshdesanisos** [comment]
Thank you @VeritasSoftware  - it is working now.
Changing the start projects and setting the correct port made the weather service working through api gateway.
![image](https://user-images.githubusercontent.com/96718718/147723592-6a7e2ad4-cba4-4c4a-9ec2-a28591a281bf.png)
