### ISSUE TITLE
feat: Newtonsoft.Json Dependecy removing

### ISSUE THREAD

**Issue by cetindogu** [VeritasSoftware/AspNetCore.ApiGateway#8]
Built in System.Text.Json can be used instead of Newtonsoft.Json

**Comment by VeritasSoftware** [comment]
Thanks for your suggestion.

This has already been done.

You can use Nuget package Release 4.1.0 or higher.

**Comment by cetindogu** [comment]
ops, i tried to remove for 5 minites ago :)  you can reject :)

https://github.com/VeritasSoftware/AspNetCore.ApiGateway/pull/9

**Comment by cetindogu** [comment]
already done.
